### ISSUE TITLE
2 errors and lots of warnings when trying to build the project in jetbrains rider

### ISSUE THREAD

**Issue by svbackend** [emt2dev/AuthReadyAPI#1]
Errors:

`Program.cs(211,11): Error CS0103 : The name 'APIUserSeeder' does not exist in the current context`

`AuthDbContext.cs(64,49): Error CS0246 : The type or namespace name 'CompanySeeder' could not be found (are you missing a using directive or an assembly reference?)`

Warnings are mostly related to not nullable properties:

`CartController.cs(25,16): Warning CS8618 : Non-nullable field '_user' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.`

Or null references:
`AuthRepository.cs(116,57): Warning CS8603 : Possible null reference return.`

As well as couple of unused fields:

`AuthRepository.cs(22,42): Warning CS0169 : The field 'AuthRepository._authRepository' is never used`

`FoodController.cs(19,22): Warning CS0169 : The field 'FoodController._user' is never used`

**Comment by emt2dev** [comment]
resolved.
